services:
  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.11
    container_name: zot
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./zot/config.json:/etc/zot/config.json:ro
      - ./keys/public.pem:/etc/zot/public.pem:ro
    depends_on:
      - minio

  proxy:
    build: ./proxy
    container_name: registry-redirect
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./keys:/keys:ro
    depends_on:
      - zot

  minio:
    image: minio/minio
    container_name: minio-server
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/distribution;
      mc mb myminio/zot;
      exit 0;
      "

  api:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./keys/private.pem:/app/keys/private.pem:ro
    environment:
      - PORT=8001

volumes:
  minio-data:
